### ISSUE TITLE
goroutine are asleep - deadlock1

### ISSUE THREAD

**Issue by YogiSOEDA** [YogiSOEDA/final-project-cli-app-database-backup-golang#1]
Semua fitur berjalan sampai selesai, tapi ada pesan error All goroutines are asleep - deadlock

Pesan error yang muncul seperti ini
![image](https://github.com/YogiSOEDA/final-project-cli-app-database-backup-golang/assets/55872560/9ebee79a-8d0d-4a52-8e61-a131a6ce07aa)

Pesan itu mengarah pada line ini
https://github.com/YogiSOEDA/final-project-cli-app-database-backup-golang/blob/7ad68ae5da4aa5fa261fc5b04b4f2dbaa2bc808f/controllers/db_backup.go#L221
https://github.com/YogiSOEDA/final-project-cli-app-database-backup-golang/blob/7ad68ae5da4aa5fa261fc5b04b4f2dbaa2bc808f/controllers/db_backup.go#L36

**Comment by pandeptwidyaop** [comment]
Bisa di solve dengan membuat sebuah goroutine untuk menunggu semua proses goroutine selesai lalu melakukan close channel, seperti code dibawah

```go

ch := make(chan model.DatabaseBackup)

wg.Add(10)

go func(){
   wg.Wait()
   close(ch)
}()


//do some work


wg.Wait()

```
